//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Hybrasyl.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o /tmp/claude-1000/-home-baughj-repos-xml/91e18c8d-51f4-4f42-8d2e-693476d3c7b5/scratchpad/xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
using System.Linq;

namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Access", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Access
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<string> _privileged;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<string> Privileged
        {
            get
            {
                return _privileged;
            }
            set
            {
                _privileged = value;
            }
        }
        /// <summary>
        /// Wire carrier for Privileged: the XSD type is an xs:list, one element
        /// containing space-separated tokens, which XmlSerializer cannot map
        /// to a typed collection. Use Privileged instead.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Privileged")]
        public string PrivilegedXmlList
        {
            get
            {
                return ((this.Privileged != null) && (this.Privileged.Count != 0))
                    ? string.Join(" ", this.Privileged) : null;
            }
            set
            {
                this.Privileged = string.IsNullOrWhiteSpace(value)
                    ? new System.Collections.Generic.List<string>()
                    : value.Split((char[])null, System.StringSplitOptions.RemoveEmptyEntries).ToList();
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Privileged collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrivilegedSpecified
        {
            get
            {
                return ((this.Privileged != null) 
                            && (this.Privileged.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Access" /> class.</para>
        /// </summary>
        public Access()
        {
            this._privileged = new System.Collections.Generic.List<string>();
            this._reserved = new System.Collections.Generic.List<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<string> _reserved;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<string> Reserved
        {
            get
            {
                return _reserved;
            }
            set
            {
                _reserved = value;
            }
        }
        /// <summary>
        /// Wire carrier for Reserved: the XSD type is an xs:list, one element
        /// containing space-separated tokens, which XmlSerializer cannot map
        /// to a typed collection. Use Reserved instead.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Reserved")]
        public string ReservedXmlList
        {
            get
            {
                return ((this.Reserved != null) && (this.Reserved.Count != 0))
                    ? string.Join(" ", this.Reserved) : null;
            }
            set
            {
                this.Reserved = string.IsNullOrWhiteSpace(value)
                    ? new System.Collections.Generic.List<string>()
                    : value.Split((char[])null, System.StringSplitOptions.RemoveEmptyEntries).ToList();
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Reserved collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReservedSpecified
        {
            get
            {
                return ((this.Reserved != null) 
                            && (this.Reserved.Count != 0));
            }
        }
    }
}
