// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.142.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class ApiEndpoints : HybrasylEntity<ApiEndpoints>
{
    #region Private fields
    private NetworkInfo _controlService;
    private TargetUrl _remoteAdminHost;
    private TargetUrl _encryptionEndpoint;
    private TargetUrl _validationEndpoint;
    private MetricsEndpoint _metricsEndpoint;
    private TargetUrl _telemetryEndpoint;
    #endregion
    
    public ApiEndpoints()
    {
        _remoteAdminHost = new TargetUrl();
        _controlService = new NetworkInfo();
    }
    
    public NetworkInfo ControlService
    {
        get
        {
            return _controlService;
        }
        set
        {
            _controlService = value;
        }
    }
    
    public TargetUrl RemoteAdminHost
    {
        get
        {
            return _remoteAdminHost;
        }
        set
        {
            _remoteAdminHost = value;
        }
    }
    
    public TargetUrl EncryptionEndpoint
    {
        get
        {
            return _encryptionEndpoint;
        }
        set
        {
            _encryptionEndpoint = value;
        }
    }
    
    public TargetUrl ValidationEndpoint
    {
        get
        {
            return _validationEndpoint;
        }
        set
        {
            _validationEndpoint = value;
        }
    }
    
    public MetricsEndpoint MetricsEndpoint
    {
        get
        {
            return _metricsEndpoint;
        }
        set
        {
            _metricsEndpoint = value;
        }
    }
    
    public TargetUrl TelemetryEndpoint
    {
        get
        {
            return _telemetryEndpoint;
        }
        set
        {
            _telemetryEndpoint = value;
        }
    }
}
}
#pragma warning restore
