// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.74.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class Appearance : HybrasylEntity<Appearance>
{
    #region Private fields
    private ushort _sprite;
    private ushort _equipSprite;
    private ushort _displaySprite;
    private ItemBodyStyle _bodyStyle;
    private ItemColor _color;
    private bool _hideBoots;
    #endregion
    
    public Appearance()
    {
        _bodyStyle = ItemBodyStyle.Transparent;
        _color = ItemColor.None;
        _hideBoots = false;
    }
    
    [XmlAttribute]
    public ushort Sprite
    {
        get
        {
            return _sprite;
        }
        set
        {
            _sprite = value;
        }
    }
    
    [XmlAttribute]
    public ushort EquipSprite
    {
        get
        {
            return _equipSprite;
        }
        set
        {
            _equipSprite = value;
        }
    }
    
    [XmlAttribute]
    public ushort DisplaySprite
    {
        get
        {
            return _displaySprite;
        }
        set
        {
            _displaySprite = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(ItemBodyStyle.Transparent)]
    public ItemBodyStyle BodyStyle
    {
        get
        {
            return _bodyStyle;
        }
        set
        {
            _bodyStyle = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(ItemColor.None)]
    public ItemColor Color
    {
        get
        {
            return _color;
        }
        set
        {
            _color = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(false)]
    public bool HideBoots
    {
        get
        {
            return _hideBoots;
        }
        set
        {
            _hideBoots = value;
        }
    }
}
}
#pragma warning restore
