//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CastableIntent", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CastableIntent
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Map")]
        public object Map { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastableLineIntent> _line;
        
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public System.Collections.Generic.List<CastableLineIntent> Line
        {
            get
            {
                return _line;
            }
            set
            {
                _line = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Line collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineSpecified
        {
            get
            {
                return ((this.Line != null) 
                            && (this.Line.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CastableIntent" /> class.</para>
        /// </summary>
        public CastableIntent()
        {
            this._line = new System.Collections.Generic.List<CastableLineIntent>();
            this._cross = new System.Collections.Generic.List<CastableCrossIntent>();
            this._square = new System.Collections.Generic.List<CastableSquareIntent>();
            this._tile = new System.Collections.Generic.List<CastableTileIntent>();
            this._cone = new System.Collections.Generic.List<CastableConeIntent>();
            this._flags = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.IntentFlags>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastableCrossIntent> _cross;
        
        [System.Xml.Serialization.XmlElementAttribute("Cross")]
        public System.Collections.Generic.List<CastableCrossIntent> Cross
        {
            get
            {
                return _cross;
            }
            set
            {
                _cross = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Cross collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CrossSpecified
        {
            get
            {
                return ((this.Cross != null) 
                            && (this.Cross.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastableSquareIntent> _square;
        
        [System.Xml.Serialization.XmlElementAttribute("Square")]
        public System.Collections.Generic.List<CastableSquareIntent> Square
        {
            get
            {
                return _square;
            }
            set
            {
                _square = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Square collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SquareSpecified
        {
            get
            {
                return ((this.Square != null) 
                            && (this.Square.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastableTileIntent> _tile;
        
        [System.Xml.Serialization.XmlElementAttribute("Tile")]
        public System.Collections.Generic.List<CastableTileIntent> Tile
        {
            get
            {
                return _tile;
            }
            set
            {
                _tile = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Tile collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TileSpecified
        {
            get
            {
                return ((this.Tile != null) 
                            && (this.Tile.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastableConeIntent> _cone;
        
        [System.Xml.Serialization.XmlElementAttribute("Cone")]
        public System.Collections.Generic.List<CastableConeIntent> Cone
        {
            get
            {
                return _cone;
            }
            set
            {
                _cone = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Cone collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConeSpecified
        {
            get
            {
                return ((this.Cone != null) 
                            && (this.Cone.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Hybrasyl.Xml.Objects.SpellUseType _useType = Hybrasyl.Xml.Objects.SpellUseType.NoTarget;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.SpellUseType.NoTarget)]
        [System.Xml.Serialization.XmlAttributeAttribute("UseType")]
        public Hybrasyl.Xml.Objects.SpellUseType UseType
        {
            get
            {
                return _useType;
            }
            set
            {
                _useType = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.IntentFlags> _flags;
        
        [System.Xml.Serialization.XmlAttributeAttribute("Flags")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.IntentFlags> Flags
        {
            get
            {
                return _flags;
            }
            set
            {
                _flags = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Flags collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagsSpecified
        {
            get
            {
                return ((this.Flags != null) 
                            && (this.Flags.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _maxTargets = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("MaxTargets")]
        public int MaxTargets
        {
            get
            {
                return _maxTargets;
            }
            set
            {
                _maxTargets = value;
            }
        }
    }
}
