//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CastableTileIntent", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CastableTileIntent
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Hybrasyl.Xml.Objects.IntentDirection _direction = Hybrasyl.Xml.Objects.IntentDirection.None;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.IntentDirection.None)]
        [System.Xml.Serialization.XmlAttributeAttribute("Direction")]
        public Hybrasyl.Xml.Objects.IntentDirection Direction
        {
            get
            {
                return _direction;
            }
            set
            {
                _direction = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private sbyte _relativeX = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("RelativeX")]
        public sbyte RelativeX
        {
            get
            {
                return _relativeX;
            }
            set
            {
                _relativeX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private sbyte _relativeY = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("RelativeY")]
        public sbyte RelativeY
        {
            get
            {
                return _relativeY;
            }
            set
            {
                _relativeY = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private VisualEffectType _visualEffect = Hybrasyl.Xml.Objects.VisualEffectType.Targets;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.VisualEffectType.Targets)]
        [System.Xml.Serialization.XmlAttributeAttribute("VisualEffect")]
        public VisualEffectType VisualEffect
        {
            get
            {
                return _visualEffect;
            }
            set
            {
                _visualEffect = value;
            }
        }
    }
}
