//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Hybrasyl.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o /tmp/claude-1000/-home-baughj-repos-xml/91e18c8d-51f4-4f42-8d2e-693476d3c7b5/scratchpad/xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Castable", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Castable", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public partial class Castable
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Description> _descriptions;
        
        [System.Xml.Serialization.XmlArrayAttribute("Descriptions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Description", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Description> Descriptions
        {
            get
            {
                return _descriptions;
            }
            set
            {
                _descriptions = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Descriptions collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescriptionsSpecified
        {
            get
            {
                return ((this.Descriptions != null) 
                            && (this.Descriptions.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Castable" /> class.</para>
        /// </summary>
        public Castable()
        {
            this._descriptions = new System.Collections.Generic.List<Description>();
            this._categories = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.Category>();
            this._castCosts = new System.Collections.Generic.List<CastCost>();
            this._intents = new System.Collections.Generic.List<CastableIntent>();
            this._requirements = new System.Collections.Generic.List<Requirement>();
            this._restrictions = new System.Collections.Generic.List<EquipmentRestriction>();
            this._elements = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.ElementType>();
            this._class = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.Class>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.Category> _categories;
        
        [System.Xml.Serialization.XmlArrayAttribute("Categories")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.Category> Categories
        {
            get
            {
                return _categories;
            }
            set
            {
                _categories = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Categories collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoriesSpecified
        {
            get
            {
                return ((this.Categories != null) 
                            && (this.Categories.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastCost> _castCosts;
        
        [System.Xml.Serialization.XmlArrayAttribute("CastCosts")]
        [System.Xml.Serialization.XmlArrayItemAttribute("CastCost", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<CastCost> CastCosts
        {
            get
            {
                return _castCosts;
            }
            set
            {
                _castCosts = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CastCosts collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CastCostsSpecified
        {
            get
            {
                return ((this.CastCosts != null) 
                            && (this.CastCosts.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastableIntent> _intents;
        
        [System.Xml.Serialization.XmlArrayAttribute("Intents")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Intent", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<CastableIntent> Intents
        {
            get
            {
                return _intents;
            }
            set
            {
                _intents = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Intents collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntentsSpecified
        {
            get
            {
                return ((this.Intents != null) 
                            && (this.Intents.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MaxLevel")]
        public MaxLevel MaxLevel { get; set; } = new MaxLevel();
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Requirement> _requirements;
        
        [System.Xml.Serialization.XmlArrayAttribute("Requirements")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Requirement> Requirements
        {
            get
            {
                return _requirements;
            }
            set
            {
                _requirements = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Requirements collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequirementsSpecified
        {
            get
            {
                return ((this.Requirements != null) 
                            && (this.Requirements.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<EquipmentRestriction> _restrictions;
        
        [System.Xml.Serialization.XmlArrayAttribute("Restrictions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<EquipmentRestriction> Restrictions
        {
            get
            {
                return _restrictions;
            }
            set
            {
                _restrictions = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Restrictions collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RestrictionsSpecified
        {
            get
            {
                return ((this.Restrictions != null) 
                            && (this.Restrictions.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Effects")]
        public CastableEffects Effects { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Script")]
        public string Script { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Mastery")]
        public CastableMastery Mastery { get; set; } = new CastableMastery();
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Icon")]
        public byte Icon { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Book")]
        public Book Book { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.ElementType> _elements;
        
        [System.Xml.Serialization.XmlAttributeAttribute("Elements")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.ElementType> Elements
        {
            get
            {
                return _elements;
            }
            set
            {
                _elements = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Elements collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElementsSpecified
        {
            get
            {
                return ((this.Elements != null) 
                            && (this.Elements.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private byte _lines = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Lines")]
        public byte Lines
        {
            get
            {
                return _lines;
            }
            set
            {
                _lines = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.Class> _class;
        
        [System.Xml.Serialization.XmlAttributeAttribute("Class")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.Class> Class
        {
            get
            {
                return _class;
            }
            set
            {
                _class = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Class collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassSpecified
        {
            get
            {
                return ((this.Class != null) 
                            && (this.Class.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _cooldown = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Cooldown")]
        public int Cooldown
        {
            get
            {
                return _cooldown;
            }
            set
            {
                _cooldown = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isAssail = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsAssail")]
        public bool IsAssail
        {
            get
            {
                return _isAssail;
            }
            set
            {
                _isAssail = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _reflectable = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Reflectable")]
        public bool Reflectable
        {
            get
            {
                return _reflectable;
            }
            set
            {
                _reflectable = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _breakStealth = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("BreakStealth")]
        public bool BreakStealth
        {
            get
            {
                return _breakStealth;
            }
            set
            {
                _breakStealth = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _includeInMetafile = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("IncludeInMetafile")]
        public bool IncludeInMetafile
        {
            get
            {
                return _includeInMetafile;
            }
            set
            {
                _includeInMetafile = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _pvpOnly = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("PvpOnly")]
        public bool PvpOnly
        {
            get
            {
                return _pvpOnly;
            }
            set
            {
                _pvpOnly = value;
            }
        }
    }
}
