//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Hybrasyl.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o /tmp/claude-1000/-home-baughj-repos-xml/91e18c8d-51f4-4f42-8d2e-693476d3c7b5/scratchpad/xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CastableReactor", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CastableReactor
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _relativeX = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("RelativeX")]
        public int RelativeX
        {
            get
            {
                return _relativeX;
            }
            set
            {
                _relativeX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _relativeY = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("RelativeY")]
        public int RelativeY
        {
            get
            {
                return _relativeY;
            }
            set
            {
                _relativeY = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ushort _sprite = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Sprite")]
        public ushort Sprite
        {
            get
            {
                return _sprite;
            }
            set
            {
                _sprite = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _script = "0";
        
        [System.ComponentModel.DefaultValueAttribute("0")]
        [System.Xml.Serialization.XmlAttributeAttribute("Script")]
        public string Script
        {
            get
            {
                return _script;
            }
            set
            {
                _script = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _expiration = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Expiration")]
        public int Expiration
        {
            get
            {
                return _expiration;
            }
            set
            {
                _expiration = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _uses = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("Uses")]
        public string Uses
        {
            get
            {
                return _uses;
            }
            set
            {
                _uses = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _blocking = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("Blocking")]
        public bool Blocking
        {
            get
            {
                return _blocking;
            }
            set
            {
                _blocking = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _displayOwner = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("DisplayOwner")]
        public bool DisplayOwner
        {
            get
            {
                return _displayOwner;
            }
            set
            {
                _displayOwner = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _displayGroup = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("DisplayGroup")]
        public bool DisplayGroup
        {
            get
            {
                return _displayGroup;
            }
            set
            {
                _displayGroup = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DisplayStatus")]
        public string DisplayStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DisplayCookie")]
        public string DisplayCookie { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DisplayName")]
        public string DisplayName { get; set; }
    }
}
