// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.185.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class CastableMastery : HybrasylEntity<CastableMastery>
{
    #region Private fields
    private int _uses;
    private List<MasteryModifier> _modifiers;
    private bool _tiered;
    #endregion
    
    public CastableMastery()
    {
        _modifiers = new List<MasteryModifier>();
        _uses = 1;
    }
    
    [XmlAttribute]
    [DefaultValue(1)]
    public int Uses
    {
        get
        {
            return _uses;
        }
        set
        {
            _uses = value;
        }
    }
    
    [XmlAttribute]
    public List<MasteryModifier> Modifiers
    {
        get
        {
            return _modifiers;
        }
        set
        {
            _modifiers = value;
        }
    }
    
    [XmlAttribute]
    public bool Tiered
    {
        get
        {
            return _tiered;
        }
        set
        {
            _tiered = value;
        }
    }
}
}
#pragma warning restore
