//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ClassCastCostStat", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClassCastCostStat
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _hp = "0";
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("0")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("Hp")]
        public string Hp
        {
            get
            {
                return _hp;
            }
            set
            {
                _hp = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _mp = "0";
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("0")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlAttributeAttribute("Mp")]
        public string Mp
        {
            get
            {
                return _mp;
            }
            set
            {
                _mp = value;
            }
        }
    }
}
