//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Hybrasyl.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o /tmp/claude-1000/-home-baughj-repos-xml/91e18c8d-51f4-4f42-8d2e-693476d3c7b5/scratchpad/xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ClassRequirementPhysical", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClassRequirementPhysical
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private byte _str = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Str")]
        public byte Str
        {
            get
            {
                return _str;
            }
            set
            {
                _str = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private byte _int = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Int")]
        public byte Int
        {
            get
            {
                return _int;
            }
            set
            {
                _int = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private byte _wis = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Wis")]
        public byte Wis
        {
            get
            {
                return _wis;
            }
            set
            {
                _wis = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private byte _con = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Con")]
        public byte Con
        {
            get
            {
                return _con;
            }
            set
            {
                _con = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private byte _dex = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Dex")]
        public byte Dex
        {
            get
            {
                return _dex;
            }
            set
            {
                _dex = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private uint _hp = 0u;
        
        [System.ComponentModel.DefaultValueAttribute(0u)]
        [System.Xml.Serialization.XmlAttributeAttribute("Hp")]
        public uint Hp
        {
            get
            {
                return _hp;
            }
            set
            {
                _hp = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private uint _mp = 0u;
        
        [System.ComponentModel.DefaultValueAttribute(0u)]
        [System.Xml.Serialization.XmlAttributeAttribute("Mp")]
        public uint Mp
        {
            get
            {
                return _mp;
            }
            set
            {
                _mp = value;
            }
        }
    }
}
