//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CreatureCastingSet", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatureCastingSet
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CreatureCastable> _castable;
        
        [System.Xml.Serialization.XmlElementAttribute("Castable")]
        public System.Collections.Generic.List<CreatureCastable> Castable
        {
            get
            {
                return _castable;
            }
            set
            {
                _castable = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Castable collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CastableSpecified
        {
            get
            {
                return ((this.Castable != null) 
                            && (this.Castable.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CreatureCastingSet" /> class.</para>
        /// </summary>
        public CreatureCastingSet()
        {
            this._castable = new System.Collections.Generic.List<CreatureCastable>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Type")]
        public RotationType Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Categories")]
        public string Categories { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _interval = 15;
        
        [System.ComponentModel.DefaultValueAttribute(15)]
        [System.Xml.Serialization.XmlAttributeAttribute("Interval")]
        public int Interval
        {
            get
            {
                return _interval;
            }
            set
            {
                _interval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CreatureTargetPriority _targetPriority = Hybrasyl.Xml.Objects.CreatureTargetPriority.HighThreat;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.CreatureTargetPriority.HighThreat)]
        [System.Xml.Serialization.XmlAttributeAttribute("TargetPriority")]
        public CreatureTargetPriority TargetPriority
        {
            get
            {
                return _targetPriority;
            }
            set
            {
                _targetPriority = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _healthPercentage = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("HealthPercentage")]
        public int HealthPercentage
        {
            get
            {
                return _healthPercentage;
            }
            set
            {
                _healthPercentage = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _random = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Random")]
        public bool Random
        {
            get
            {
                return _random;
            }
            set
            {
                _random = value;
            }
        }
    }
}
