//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CreatureBehavior", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatureBehavior
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CreatureCastingSet> _castingSets;
        
        [System.Xml.Serialization.XmlArrayAttribute("CastingSets")]
        [System.Xml.Serialization.XmlArrayItemAttribute("CastingSet", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<CreatureCastingSet> CastingSets
        {
            get
            {
                return _castingSets;
            }
            set
            {
                _castingSets = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CastingSets collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CastingSetsSpecified
        {
            get
            {
                return ((this.CastingSets != null) 
                            && (this.CastingSets.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CreatureBehavior" /> class.</para>
        /// </summary>
        public CreatureBehavior()
        {
            this._castingSets = new System.Collections.Generic.List<CreatureCastingSet>();
            this._setCookies = new System.Collections.Generic.List<CreatureCookie>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Hostility")]
        public CreatureHostilitySettings Hostility { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CreatureCookie> _setCookies;
        
        [System.Xml.Serialization.XmlArrayAttribute("SetCookies")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Cookie", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<CreatureCookie> SetCookies
        {
            get
            {
                return _setCookies;
            }
            set
            {
                _setCookies = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SetCookies collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SetCookiesSpecified
        {
            get
            {
                return ((this.SetCookies != null) 
                            && (this.SetCookies.Count != 0));
            }
        }
    }
}
