// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.74.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
[XmlRootAttribute("BehaviorSet", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02", IsNullable=false)]
public partial class CreatureBehaviorSet : HybrasylXmlEntity<CreatureBehaviorSet>
{
    #region Private fields
    private string _statAlloc;
    private CreatureCastables _castables;
    private CreatureBehavior _behavior;
    private List<string> _immunities;
    private string _name;
    private string _import;
    #endregion
    
    public string StatAlloc
    {
        get
        {
            return _statAlloc;
        }
        set
        {
            _statAlloc = value;
        }
    }
    
    public CreatureCastables Castables
    {
        get
        {
            return _castables;
        }
        set
        {
            _castables = value;
        }
    }
    
    public CreatureBehavior Behavior
    {
        get
        {
            return _behavior;
        }
        set
        {
            _behavior = value;
        }
    }
    
    [XmlArrayItemAttribute("Immunity", IsNullable=false)]
    public List<string> Immunities
    {
        get
        {
            return _immunities;
        }
        set
        {
            _immunities = value;
        }
    }
    
    [XmlAttribute]
    public string Name
    {
        get
        {
            return _name;
        }
        set
        {
            _name = value;
        }
    }
    
    [XmlAttribute]
    public string Import
    {
        get
        {
            return _import;
        }
        set
        {
            _import = value;
        }
    }
}
}
#pragma warning restore
