// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.142.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
[XmlRootAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02", IsNullable=false)]
public partial class ElementTable : HybrasylEntity<ElementTable>
{
    #region Private fields
    private List<ElementTableSourceElement> _source;
    private string _name;
    #endregion
    
    public ElementTable()
    {
        _source = new List<ElementTableSourceElement>();
        _name = "default";
    }
    
    [XmlElement("Source")]
    public List<ElementTableSourceElement> Source
    {
        get
        {
            return _source;
        }
        set
        {
            _source = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue("default")]
    public string Name
    {
        get
        {
            return _name;
        }
        set
        {
            _name = value;
        }
    }
}
}
#pragma warning restore
