//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EquipmentSlot", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public enum EquipmentSlot
    {
        
        None = 0,
        
        Weapon = 1,
        
        Armor = 2,
        
        Shield = 3,
        
        Helmet = 4,
        
        Earring = 5,
        
        Necklace = 6,
        
        LeftHand = 7,
        
        RightHand = 8,
        
        LeftArm = 9,
        
        RightArm = 10,
        
        Waist = 11,
        
        Leg = 12,
        
        Foot = 13,
        
        FirstAcc = 14,
        
        Trousers = 15,
        
        Coat = 16,
        
        SecondAcc = 17,
        
        ThirdAcc = 18,
        
        Gauntlet = 19,
        
        Ring = 20,
    }
}
