//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Enums
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemTag", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public enum ItemTag
    {
        
        Junk = 0,
        
        Common = 1,
        
        Reagent = 2,
        
        Magic = 3,
        
        Rare = 4,
        
        Masterwork = 5,
        
        Legendary = 6,
        
        Artifact = 7,
        
        Religious = 8,
        
        Social = 9,
        
        Academic = 10,
        
        Quest = 11,
        
        Political = 12,
        
        Currency = 13,
        
        Peasantware = 14,
        
        Armor = 15,
        
        Weapon = 16,
        
        Contraption = 17,
        
        Food = 18,
        
        Tool = 19,
        
        Adornment = 20,
    }
}
