//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemRestrictions", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemRestrictions
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Level")]
        public RestrictionsLevel Level { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Ab")]
        public RestrictionsAb Ab { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Hybrasyl.Xml.Objects.Class _class = Hybrasyl.Xml.Objects.Class.Peasant;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.Class.Peasant)]
        [System.Xml.Serialization.XmlElementAttribute("Class")]
        public Hybrasyl.Xml.Objects.Class Class
        {
            get
            {
                return _class;
            }
            set
            {
                _class = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Hybrasyl.Xml.Objects.Gender _gender = Hybrasyl.Xml.Objects.Gender.Neutral;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.Gender.Neutral)]
        [System.Xml.Serialization.XmlElementAttribute("Gender")]
        public Hybrasyl.Xml.Objects.Gender Gender
        {
            get
            {
                return _gender;
            }
            set
            {
                _gender = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<string> _castables;
        
        [System.Xml.Serialization.XmlArrayAttribute("Castables")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Castable", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<string> Castables
        {
            get
            {
                return _castables;
            }
            set
            {
                _castables = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Castables collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CastablesSpecified
        {
            get
            {
                return ((this.Castables != null) 
                            && (this.Castables.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ItemRestrictions" /> class.</para>
        /// </summary>
        public ItemRestrictions()
        {
            this._castables = new System.Collections.Generic.List<string>();
            this._slotRestrictions = new System.Collections.Generic.List<SlotRestriction>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<SlotRestriction> _slotRestrictions;
        
        [System.Xml.Serialization.XmlArrayAttribute("SlotRestrictions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SlotRestriction", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<SlotRestriction> SlotRestrictions
        {
            get
            {
                return _slotRestrictions;
            }
            set
            {
                _slotRestrictions = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SlotRestrictions collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SlotRestrictionsSpecified
        {
            get
            {
                return ((this.SlotRestrictions != null) 
                            && (this.SlotRestrictions.Count != 0));
            }
        }
    }
}
