// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.185.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class ItemDamage : HybrasylEntity<ItemDamage>
{
    #region Private fields
    private float _largeMin;
    private float _largeMax;
    private float _smallMin;
    private float _smallMax;
    #endregion
    
    public ItemDamage()
    {
        _largeMin = ((float)(0F));
        _largeMax = ((float)(0F));
    }
    
    [XmlAttribute]
    [DefaultValue(typeof(float), "0")]
    public float LargeMin
    {
        get
        {
            return _largeMin;
        }
        set
        {
            _largeMin = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(typeof(float), "0")]
    public float LargeMax
    {
        get
        {
            return _largeMax;
        }
        set
        {
            _largeMax = value;
        }
    }
    
    [XmlAttribute]
    public float SmallMin
    {
        get
        {
            return _smallMin;
        }
        set
        {
            _smallMin = value;
        }
    }
    
    [XmlAttribute]
    public float SmallMax
    {
        get
        {
            return _smallMax;
        }
        set
        {
            _smallMax = value;
        }
    }
}
}
#pragma warning restore
