//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Item", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Item", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public partial class Item
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("UnidentifiedName")]
        public string UnidentifiedName { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 65534.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(65534)]
        [System.Xml.Serialization.XmlElementAttribute("Comment")]
        public string Comment { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Properties")]
        public ItemProperties Properties { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _includeInMetafile = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("IncludeInMetafile")]
        public bool IncludeInMetafile
        {
            get
            {
                return _includeInMetafile;
            }
            set
            {
                _includeInMetafile = value;
            }
        }
    }
}
