//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemColor", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public enum ItemColor
    {
        
        None = 0,
        
        Black = 1,
        
        Red = 2,
        
        Auburn = 3,
        
        Butter = 4,
        
        Aqua = 5,
        
        Blue = 6,
        
        Plum = 7,
        
        Forest = 8,
        
        Green = 9,
        
        Sienna = 10,
        
        Brown = 11,
        
        Charcoal = 12,
        
        Navy = 13,
        
        Acorn = 14,
        
        White = 15,
        
        Pink = 16,
        
        Honeydew = 17,
        
        Orange = 18,
        
        Platinum = 19,
        
        Midnight = 20,
        
        Orchid = 21,
        
        Lavender = 22,
        
        Fuschia = 23,
        
        Cerise = 24,
        
        Ocean = 25,
        
        HotPink = 26,
        
        Seafoam = 27,
        
        Amethyst = 28,
        
        Peach = 29,
        
        Sky = 30,
        
        Lime = 31,
        
        Jade = 32,
        
        Honey = 33,
        
        Cobalt = 34,
        
        Cocoa = 35,
        
        Wine = 36,
        
        Kelp = 37,
        
        Wine2 = 38,
        
        Teal = 39,
        
        Copper = 40,
        
        Curry = 41,
        
        Moss = 42,
        
        Grass = 43,
        
        Lapis = 44,
        
        Maroon = 45,
        
        TiNfOiL = 46,
        
        Aquamarine = 47,
        
        Leaf = 48,
        
        Purple = 49,
        
        Scarlet = 50,
        
        Lemon = 51,
        
        Puce = 52,
        
        Coral = 53,
        
        Crimson = 54,
        
        Gold = 55,
        
        Silver = 56,
        
        Fire = 57,
        
        Stormy = 58,
        
        Cherry = 59,
        
        Mint = 60,
        
        Cerulean = 61,
        
        Twilight = 62,
        
        Quartz = 63,
        
        Turquoise = 64,
        
        Peridot = 65,
        
        Nebula = 66,
        
        Bubblegum = 67,
        
        Cyan = 68,
        
        Sable = 69,
        
        Mauve = 70,
        
        Dusk = 71,
    }
}
