// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.74.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public enum ItemTags
{
    Junk = 1,
    Common = 2,
    Reagent = 4,
    Magic = 8,
    Rare = 16,
    Masterwork = 32,
    Legendary = 64,
    Artifact = 128,
    Religious = 256,
    Social = 512,
    Academic = 1024,
    Quest = 2048,
    Political = 4096,
    Currency = 8192,
    Peasantware = 16384,
    Armor = 32768,
    Weapon = 65536,
    Contraption = 131072,
    Food = 262144,
    Tool = 524288,
    Adornment = 1048576,
}
}
#pragma warning restore
