//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemProperties", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemProperties
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Appearance")]
        public Appearance Appearance { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CastModifier> _castModifiers;
        
        [System.Xml.Serialization.XmlArrayAttribute("CastModifiers")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Match", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<CastModifier> CastModifiers
        {
            get
            {
                return _castModifiers;
            }
            set
            {
                _castModifiers = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CastModifiers collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CastModifiersSpecified
        {
            get
            {
                return ((this.CastModifiers != null) 
                            && (this.CastModifiers.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ItemProperties" /> class.</para>
        /// </summary>
        public ItemProperties()
        {
            this._castModifiers = new System.Collections.Generic.List<CastModifier>();
            this._categories = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.Category>();
            this._flags = default(ItemFlags);
            this._motions = new System.Collections.Generic.List<ItemMotion>();
            this._procs = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.Proc>();
            this._tags = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.ItemTag>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Stackable")]
        public Stackable Stackable { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Physical")]
        public Physical Physical { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.Category> _categories;
        
        [System.Xml.Serialization.XmlArrayAttribute("Categories")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.Category> Categories
        {
            get
            {
                return _categories;
            }
            set
            {
                _categories = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Categories collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoriesSpecified
        {
            get
            {
                return ((this.Categories != null) 
                            && (this.Categories.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Equipment")]
        public Equipment Equipment { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StatModifiers")]
        public Hybrasyl.Xml.Objects.StatModifiers StatModifiers { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ItemFlags _flags;
        
        [System.Xml.Serialization.XmlElementAttribute("Flags")]
        public ItemFlags Flags
        {
            get
            {
                return _flags;
            }
            set
            {
                _flags = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Flags collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagsSpecified
        {
            get
            {
                return (this.Flags != default(ItemFlags));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Variants")]
        public Variants Variants { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Vendor")]
        public Vendor Vendor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Damage")]
        public ItemDamage Damage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Use")]
        public Use Use { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Restrictions")]
        public ItemRestrictions Restrictions { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ItemMotion> _motions;
        
        [System.Xml.Serialization.XmlArrayAttribute("Motions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Motion", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<ItemMotion> Motions
        {
            get
            {
                return _motions;
            }
            set
            {
                _motions = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Motions collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MotionsSpecified
        {
            get
            {
                return ((this.Motions != null) 
                            && (this.Motions.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.Proc> _procs;
        
        [System.Xml.Serialization.XmlArrayAttribute("Procs")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Proc", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.Proc> Procs
        {
            get
            {
                return _procs;
            }
            set
            {
                _procs = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Procs collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcsSpecified
        {
            get
            {
                return ((this.Procs != null) 
                            && (this.Procs.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.ItemTag> _tags;
        
        [System.Xml.Serialization.XmlAttributeAttribute("Tags")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.ItemTag> Tags
        {
            get
            {
                return _tags;
            }
            set
            {
                _tags = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Tags collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TagsSpecified
        {
            get
            {
                return ((this.Tags != null) 
                            && (this.Tags.Count != 0));
            }
        }
    }
}
