//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Localization", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Localization", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public partial class Localization
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> _common;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("Common")]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> Common
        {
            get
            {
                return _common;
            }
            set
            {
                _common = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Localization" /> class.</para>
        /// </summary>
        public Localization()
        {
            this._common = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString>();
            this._merchant = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString>();
            this._npcSpeak = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString>();
            this._monsterSpeak = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString>();
            this._npcResponses = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.NpcResponse>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> _merchant;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("Merchant")]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> Merchant
        {
            get
            {
                return _merchant;
            }
            set
            {
                _merchant = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> _npcSpeak;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("NpcSpeak")]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> NpcSpeak
        {
            get
            {
                return _npcSpeak;
            }
            set
            {
                _npcSpeak = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> _monsterSpeak;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("MonsterSpeak")]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.LocalizedString> MonsterSpeak
        {
            get
            {
                return _monsterSpeak;
            }
            set
            {
                _monsterSpeak = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.NpcResponse> _npcResponses;
        
        [System.Xml.Serialization.XmlArrayAttribute("NpcResponses")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.NpcResponse> NpcResponses
        {
            get
            {
                return _npcResponses;
            }
            set
            {
                _npcResponses = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NpcResponses collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NpcResponsesSpecified
        {
            get
            {
                return ((this.NpcResponses != null) 
                            && (this.NpcResponses.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Locale")]
        public string Locale { get; set; }
    }
}
