// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.185.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class LogGlobalConfig : HybrasylEntity<LogGlobalConfig>
{
    #region Private fields
    private List<LogConfig> _log;
    private bool _singleStreamEnabled;
    private bool _jsonOutputEnabled;
    private LogLevel _minimumLevel;
    #endregion
    
    public LogGlobalConfig()
    {
        _singleStreamEnabled = false;
        _jsonOutputEnabled = false;
        _minimumLevel = LogLevel.Info;
    }
    
    [XmlElement("Log")]
    public List<LogConfig> Log
    {
        get
        {
            return _log;
        }
        set
        {
            _log = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(false)]
    public bool SingleStreamEnabled
    {
        get
        {
            return _singleStreamEnabled;
        }
        set
        {
            _singleStreamEnabled = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(false)]
    public bool JsonOutputEnabled
    {
        get
        {
            return _jsonOutputEnabled;
        }
        set
        {
            _jsonOutputEnabled = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(LogLevel.Info)]
    public LogLevel MinimumLevel
    {
        get
        {
            return _minimumLevel;
        }
        set
        {
            _minimumLevel = value;
        }
    }
}
}
#pragma warning restore
