//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LootTable", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LootTable
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<LootTableItemList> _items;
        
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public System.Collections.Generic.List<LootTableItemList> Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Items collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemsSpecified
        {
            get
            {
                return ((this.Items != null) 
                            && (this.Items.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="LootTable" /> class.</para>
        /// </summary>
        public LootTable()
        {
            this._items = new System.Collections.Generic.List<LootTableItemList>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Gold")]
        public LootTableGold Gold { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Xp")]
        public LootTableXp Xp { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _rolls = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("Rolls")]
        public int Rolls
        {
            get
            {
                return _rolls;
            }
            set
            {
                _rolls = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private double _chance = 0D;
        
        [System.ComponentModel.DefaultValueAttribute(0D)]
        [System.Xml.Serialization.XmlAttributeAttribute("Chance")]
        public double Chance
        {
            get
            {
                return _chance;
            }
            set
            {
                _chance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _inInventory = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("InInventory")]
        public bool InInventory
        {
            get
            {
                return _inInventory;
            }
            set
            {
                _inInventory = value;
            }
        }
    }
}
