// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.74.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class LootItem : HybrasylEntity<LootItem>
{
    #region Private fields
    private int _max;
    private bool _unique;
    private bool _always;
    private List<string> _variants;
    private string _value;
    #endregion
    
    public LootItem()
    {
        _variants = new List<string>();
        _max = 0;
        _unique = false;
        _always = false;
    }
    
    [XmlAttribute]
    [DefaultValue(0)]
    public int Max
    {
        get
        {
            return _max;
        }
        set
        {
            _max = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(false)]
    public bool Unique
    {
        get
        {
            return _unique;
        }
        set
        {
            _unique = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(false)]
    public bool Always
    {
        get
        {
            return _always;
        }
        set
        {
            _always = value;
        }
    }
    
    [XmlAttribute]
    public List<string> Variants
    {
        get
        {
            return _variants;
        }
        set
        {
            _variants = value;
        }
    }
    
    [XmlTextAttribute]
    public string Value
    {
        get
        {
            return _value;
        }
        set
        {
            _value = value;
        }
    }
}
}
#pragma warning restore
