// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.185.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class MessagePlugin : HybrasylEntity<MessagePlugin>
{
    #region Private fields
    private List<PluginConfig> _configuration;
    private List<string> _targets;
    private MessageType _type;
    private bool _passthrough;
    private string _name;
    #endregion
    
    [XmlArrayItemAttribute("Config", IsNullable=false)]
    public List<PluginConfig> Configuration
    {
        get
        {
            return _configuration;
        }
        set
        {
            _configuration = value;
        }
    }
    
    [XmlArrayItemAttribute("Target", DataType="token", IsNullable=false)]
    public List<string> Targets
    {
        get
        {
            return _targets;
        }
        set
        {
            _targets = value;
        }
    }
    
    [XmlAttribute]
    public MessageType Type
    {
        get
        {
            return _type;
        }
        set
        {
            _type = value;
        }
    }
    
    [XmlAttribute]
    public bool Passthrough
    {
        get
        {
            return _passthrough;
        }
        set
        {
            _passthrough = value;
        }
    }
    
    [XmlAttribute(DataType="token")]
    public string Name
    {
        get
        {
            return _name;
        }
        set
        {
            _name = value;
        }
    }
}
}
#pragma warning restore
