//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MessageHandlers", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageHandlers
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MessageHandler> _mail;
        
        [System.Xml.Serialization.XmlElementAttribute("Mail")]
        public System.Collections.Generic.List<MessageHandler> Mail
        {
            get
            {
                return _mail;
            }
            set
            {
                _mail = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Mail collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MailSpecified
        {
            get
            {
                return ((this.Mail != null) 
                            && (this.Mail.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MessageHandlers" /> class.</para>
        /// </summary>
        public MessageHandlers()
        {
            this._mail = new System.Collections.Generic.List<MessageHandler>();
            this._board = new System.Collections.Generic.List<MessageHandler>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MessageHandler> _board;
        
        [System.Xml.Serialization.XmlElementAttribute("Board")]
        public System.Collections.Generic.List<MessageHandler> Board
        {
            get
            {
                return _board;
            }
            set
            {
                _board = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Board collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoardSpecified
        {
            get
            {
                return ((this.Board != null) 
                            && (this.Board.Count != 0));
            }
        }
    }
}
