// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.142.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class MetricsEndpoint : HybrasylEntity<MetricsEndpoint>
{
    #region Private fields
    private string _apiKey;
    private string _url;
    #endregion
    
    [XmlAttribute]
    public string ApiKey
    {
        get
        {
            return _apiKey;
        }
        set
        {
            _apiKey = value;
        }
    }
    
    [XmlAttribute(DataType="anyURI")]
    public string Url
    {
        get
        {
            return _url;
        }
        set
        {
            _url = value;
        }
    }
}
}
#pragma warning restore
