//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NetworkInfo", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NetworkInfo
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _bindAddress = "127.0.0.1";
        
        /// <summary>
        /// <para xml:lang="en">Pattern: ((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\.){3}((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9])))(\-((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\.){3}((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))))?.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("127.0.0.1")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|([01" +
            "]?[0-9]?[0-9])))(\\-((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\\.){3}((25[0-5]" +
            ")|(2[0-4][0-9])|([01]?[0-9]?[0-9]))))?"))]
        [System.Xml.Serialization.XmlAttributeAttribute("BindAddress")]
        public string BindAddress
        {
            get
            {
                return _bindAddress;
            }
            set
            {
                _bindAddress = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: ((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\.){3}((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9])))(\-((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\.){3}((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))))?.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\\.){3}((25[0-5])|(2[0-4][0-9])|([01" +
            "]?[0-9]?[0-9])))(\\-((((25[0-5])|(2[0-4][0-9])|([01]?[0-9]?[0-9]))\\.){3}((25[0-5]" +
            ")|(2[0-4][0-9])|([01]?[0-9]?[0-9]))))?"))]
        [System.Xml.Serialization.XmlAttributeAttribute("ExternalAddress")]
        public string ExternalAddress { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Port")]
        public ushort Port { get; set; }
    }
}
