// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.185.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class NetworkInfo : HybrasylEntity<NetworkInfo>
{
    #region Private fields
    private string _bindAddress;
    private string _externalAddress;
    private ushort _port;
    #endregion
    
    public NetworkInfo()
    {
        _bindAddress = "127.0.0.1";
    }
    
    [XmlAttribute]
    [DefaultValue("127.0.0.1")]
    public string BindAddress
    {
        get
        {
            return _bindAddress;
        }
        set
        {
            _bindAddress = value;
        }
    }
    
    [XmlAttribute]
    public string ExternalAddress
    {
        get
        {
            return _externalAddress;
        }
        set
        {
            _externalAddress = value;
        }
    }
    
    [XmlAttribute]
    public ushort Port
    {
        get
        {
            return _port;
        }
        set
        {
            _port = value;
        }
    }
}
}
#pragma warning restore
