//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Hybrasyl.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o /tmp/claude-1000/-home-baughj-repos-xml/91e18c8d-51f4-4f42-8d2e-693476d3c7b5/scratchpad/xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Npc", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Npc", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public partial class Npc
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("DisplayName")]
        public string DisplayName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Appearance")]
        public NpcAppearance Appearance { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<LocalizedString> _strings;
        
        [System.Xml.Serialization.XmlArrayAttribute("Strings")]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<LocalizedString> Strings
        {
            get
            {
                return _strings;
            }
            set
            {
                _strings = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Strings collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StringsSpecified
        {
            get
            {
                return ((this.Strings != null) 
                            && (this.Strings.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Npc" /> class.</para>
        /// </summary>
        public Npc()
        {
            this._strings = new System.Collections.Generic.List<LocalizedString>();
            this._responses = new System.Collections.Generic.List<NpcResponse>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NpcResponse> _responses;
        
        [System.Xml.Serialization.XmlArrayAttribute("Responses")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<NpcResponse> Responses
        {
            get
            {
                return _responses;
            }
            set
            {
                _responses = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Responses collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponsesSpecified
        {
            get
            {
                return ((this.Responses != null) 
                            && (this.Responses.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Roles")]
        public NpcRoleList Roles { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AllowDead")]
        public bool AllowDead { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AllowDead property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowDeadSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Inventory")]
        public NpcInventory Inventory { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("X")]
        public byte X { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Y")]
        public byte Y { get; set; }
    }
}
