//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NpcRoleList", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NpcRoleList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NpcRoleTrainCastable> _train;
        
        [System.Xml.Serialization.XmlArrayAttribute("Train")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Castable", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<NpcRoleTrainCastable> Train
        {
            get
            {
                return _train;
            }
            set
            {
                _train = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Train collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrainSpecified
        {
            get
            {
                return ((this.Train != null) 
                            && (this.Train.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NpcRoleList" /> class.</para>
        /// </summary>
        public NpcRoleList()
        {
            this._train = new System.Collections.Generic.List<NpcRoleTrainCastable>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Vend")]
        public NpcRoleVend Vend { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Post")]
        public NpcRolePost Post { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Repair")]
        public NpcRoleRepair Repair { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Bank")]
        public NpcRoleBank Bank { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _disableForget = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("DisableForget")]
        public bool DisableForget
        {
            get
            {
                return _disableForget;
            }
            set
            {
                _disableForget = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TrainCheck")]
        public string TrainCheck { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("VendCheck")]
        public string VendCheck { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PostCheck")]
        public string PostCheck { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RepairCheck")]
        public string RepairCheck { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BankCheck")]
        public string BankCheck { get; set; }
    }
}
