//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Physical", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Physical
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _value = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("Value")]
        public float Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _weight = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("Weight")]
        public float Weight
        {
            get
            {
                return _weight;
            }
            set
            {
                _weight = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _durability = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("Durability")]
        public float Durability
        {
            get
            {
                return _durability;
            }
            set
            {
                _durability = value;
            }
        }
    }
}
