//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServerConfig", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ServerConfig", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    public partial class ServerConfig
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Logging")]
        public LogGlobalConfig Logging { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataStore")]
        public DataStore DataStore { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Network")]
        public Network Network { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ApiEndpoints")]
        public ApiEndpoints ApiEndpoints { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Access")]
        public Access Access { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<GlobalBoard> _boards;
        
        [System.Xml.Serialization.XmlArrayAttribute("Boards")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Board", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<GlobalBoard> Boards
        {
            get
            {
                return _boards;
            }
            set
            {
                _boards = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Boards collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoardsSpecified
        {
            get
            {
                return ((this.Boards != null) 
                            && (this.Boards.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServerConfig" /> class.</para>
        /// </summary>
        public ServerConfig()
        {
            this._boards = new System.Collections.Generic.List<GlobalBoard>();
            this._clientSettings = new System.Collections.Generic.List<ClientSetting>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Time")]
        public Time Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Handlers")]
        public Handlers Handlers { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 65534.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(65534)]
        [System.Xml.Serialization.XmlElementAttribute("Motd")]
        public string Motd { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Plugins")]
        public ServerPlugins Plugins { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ClientSetting> _clientSettings;
        
        [System.Xml.Serialization.XmlArrayAttribute("ClientSettings")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<ClientSetting> ClientSettings
        {
            get
            {
                return _clientSettings;
            }
            set
            {
                _clientSettings = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ClientSettings collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClientSettingsSpecified
        {
            get
            {
                return ((this.ClientSettings != null) 
                            && (this.ClientSettings.Count != 0));
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Constants")]
        public ServerConstants Constants { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Formulas")]
        public ServerFormulas Formulas { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _name = "default";
        
        [System.ComponentModel.DefaultValueAttribute("default")]
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _elementTable = "default";
        
        [System.ComponentModel.DefaultValueAttribute("default")]
        [System.Xml.Serialization.XmlAttributeAttribute("ElementTable")]
        public string ElementTable
        {
            get
            {
                return _elementTable;
            }
            set
            {
                _elementTable = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _locale = "en_us";
        
        [System.ComponentModel.DefaultValueAttribute("en_us")]
        [System.Xml.Serialization.XmlAttributeAttribute("Locale")]
        public string Locale
        {
            get
            {
                return _locale;
            }
            set
            {
                _locale = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _environment = "dev";
        
        [System.ComponentModel.DefaultValueAttribute("dev")]
        [System.Xml.Serialization.XmlAttributeAttribute("Environment")]
        public string Environment
        {
            get
            {
                return _environment;
            }
            set
            {
                _environment = value;
            }
        }
    }
}
