//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServerFormulas", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServerFormulas
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _xpToNextLevel = "Pow(SOURCELEVEL,3)*250";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("XpToNextLevel")]
        public string XpToNextLevel
        {
            get
            {
                return _xpToNextLevel;
            }
            set
            {
                _xpToNextLevel = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _hpGainPerLevel = "((SOURCECON/(SOURCELEVEL + 1)*50)*(RANDDOUBLE*0.30+0.85))+25";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("HpGainPerLevel")]
        public string HpGainPerLevel
        {
            get
            {
                return _hpGainPerLevel;
            }
            set
            {
                _hpGainPerLevel = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _mpGainPerLevel = "((SOURCEWIS/(SOURCELEVEL + 1)*50)*(RANDDOUBLE*0.30+0.85))+25";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MpGainPerLevel")]
        public string MpGainPerLevel
        {
            get
            {
                return _mpGainPerLevel;
            }
            set
            {
                _mpGainPerLevel = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _allowedCarryWeight = "SOURCESTR+(SOURCELEVEL/4) + 48";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AllowedCarryWeight")]
        public string AllowedCarryWeight
        {
            get
            {
                return _allowedCarryWeight;
            }
            set
            {
                _allowedCarryWeight = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _allowedEquipmentWeight = "(SOURCESTR+(SOURCELEVEL/4) + 48)/2";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AllowedEquipmentWeight")]
        public string AllowedEquipmentWeight
        {
            get
            {
                return _allowedEquipmentWeight;
            }
            set
            {
                _allowedEquipmentWeight = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _mpRegenPerTick = ("Min(SOURCEMAXIMUMMP * (0.1 + Max(SOURCEWIS, SOURCEWIS - SOURCELEVEL) * 0.01), SOU" +
            "RCEMAXIMUMMP * 0.20)");
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MpRegenPerTick")]
        public string MpRegenPerTick
        {
            get
            {
                return _mpRegenPerTick;
            }
            set
            {
                _mpRegenPerTick = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _hpRegenPerTick = ("Min(SOURCEMAXIMUMHP * (0.1 + Max(SOURCECON, SOURCECON - SOURCELEVEL) * 0.01), SOU" +
            "RCEMAXIMUMHP * 0.20)");
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("HpRegenPerTick")]
        public string HpRegenPerTick
        {
            get
            {
                return _hpRegenPerTick;
            }
            set
            {
                _hpRegenPerTick = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _acDamageMitigation = "";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AcDamageMitigation")]
        public string AcDamageMitigation
        {
            get
            {
                return _acDamageMitigation;
            }
            set
            {
                _acDamageMitigation = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _acMagicDamageMitigation = "";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AcMagicDamageMitigation")]
        public string AcMagicDamageMitigation
        {
            get
            {
                return _acMagicDamageMitigation;
            }
            set
            {
                _acMagicDamageMitigation = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _monsterHpGainPerLevel = "((SOURCECON/(SOURCELEVEL + 1)*50)*(RANDDOUBLE*0.30+0.85))+25";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MonsterHpGainPerLevel")]
        public string MonsterHpGainPerLevel
        {
            get
            {
                return _monsterHpGainPerLevel;
            }
            set
            {
                _monsterHpGainPerLevel = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _monsterMpGainPerLevel = "((SOURCEWIS/(SOURCELEVEL + 1)*50)*(RANDDOUBLE*0.30+0.85))+25";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MonsterMpGainPerLevel")]
        public string MonsterMpGainPerLevel
        {
            get
            {
                return _monsterMpGainPerLevel;
            }
            set
            {
                _monsterMpGainPerLevel = value;
            }
        }
    }
}
