//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen /home/baughj/repos/xml/src/XSD/Castable.xsd /home/baughj/repos/xml/src/XSD/Common.xsd /home/baughj/repos/xml/src/XSD/Creature.xsd /home/baughj/repos/xml/src/XSD/ElementTable.xsd /home/baughj/repos/xml/src/XSD/Hybrasyl.xsd /home/baughj/repos/xml/src/XSD/Item.xsd /home/baughj/repos/xml/src/XSD/Localization.xsd /home/baughj/repos/xml/src/XSD/Loot.xsd /home/baughj/repos/xml/src/XSD/Map.xsd /home/baughj/repos/xml/src/XSD/Nation.xsd /home/baughj/repos/xml/src/XSD/Recipe.xsd /home/baughj/repos/xml/src/XSD/ServerConfig.xsd /home/baughj/repos/xml/src/XSD/Spawns.xsd /home/baughj/repos/xml/src/XSD/Status.xsd -o xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServerStart", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServerStart
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute(DataType="dateTime")]
        public System.DateTime Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _defaultAge = "Hybrasyl";
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("Hybrasyl")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlAttributeAttribute("DefaultAge")]
        public string DefaultAge
        {
            get
            {
                return _defaultAge;
            }
            set
            {
                _defaultAge = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _defaultYear = 1;
        
        [System.ComponentModel.DefaultValueAttribute(1)]
        [System.Xml.Serialization.XmlAttributeAttribute("DefaultYear")]
        public int DefaultYear
        {
            get
            {
                return _defaultYear;
            }
            set
            {
                _defaultYear = value;
            }
        }
    }
}
