//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServerConstants", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServerConstants
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _merchantBuybackPercentage = 0.2F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MerchantBuybackPercentage")]
        public float MerchantBuybackPercentage
        {
            get
            {
                return _merchantBuybackPercentage;
            }
            set
            {
                _merchantBuybackPercentage = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerMaxLevel = 99;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxLevel")]
        public int PlayerMaxLevel
        {
            get
            {
                return _playerMaxLevel;
            }
            set
            {
                _playerMaxLevel = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _viewportSize = 24;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ViewportSize")]
        public int ViewportSize
        {
            get
            {
                return _viewportSize;
            }
            set
            {
                _viewportSize = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerMaxBookSize = 90;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxBookSize")]
        public int PlayerMaxBookSize
        {
            get
            {
                return _playerMaxBookSize;
            }
            set
            {
                _playerMaxBookSize = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerMaxDropDistance = 2;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxDropDistance")]
        public int PlayerMaxDropDistance
        {
            get
            {
                return _playerMaxDropDistance;
            }
            set
            {
                _playerMaxDropDistance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerPickupDistance = 2;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerPickupDistance")]
        public int PlayerPickupDistance
        {
            get
            {
                return _playerPickupDistance;
            }
            set
            {
                _playerPickupDistance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerExchangeDistance = 2;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerExchangeDistance")]
        public int PlayerExchangeDistance
        {
            get
            {
                return _playerExchangeDistance;
            }
            set
            {
                _playerExchangeDistance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerMaxCastDistance = 12;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxCastDistance")]
        public int PlayerMaxCastDistance
        {
            get
            {
                return _playerMaxCastDistance;
            }
            set
            {
                _playerMaxCastDistance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private uint _playerMaxGold = 1000000000u;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxGold")]
        public uint PlayerMaxGold
        {
            get
            {
                return _playerMaxGold;
            }
            set
            {
                _playerMaxGold = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _itemVariantIdStart = 100000;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ItemVariantIdStart")]
        public int ItemVariantIdStart
        {
            get
            {
                return _itemVariantIdStart;
            }
            set
            {
                _itemVariantIdStart = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _logDefaultLevels = 1;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LogDefaultLevels")]
        public int LogDefaultLevels
        {
            get
            {
                return _logDefaultLevels;
            }
            set
            {
                _logDefaultLevels = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerGroupSharingDistance = 20;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerGroupSharingDistance")]
        public int PlayerGroupSharingDistance
        {
            get
            {
                return _playerGroupSharingDistance;
            }
            set
            {
                _playerGroupSharingDistance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerAsyncDialogDistance = 10;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerAsyncDialogDistance")]
        public int PlayerAsyncDialogDistance
        {
            get
            {
                return _playerAsyncDialogDistance;
            }
            set
            {
                _playerAsyncDialogDistance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _lagMap = 1001;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LagMap")]
        public int LagMap
        {
            get
            {
                return _lagMap;
            }
            set
            {
                _lagMap = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _nationalSpawnTimeout = 10800;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NationalSpawnTimeout")]
        public int NationalSpawnTimeout
        {
            get
            {
                return _nationalSpawnTimeout;
            }
            set
            {
                _nationalSpawnTimeout = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _deathpileGroupTimeout = 0;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DeathpileGroupTimeout")]
        public int DeathpileGroupTimeout
        {
            get
            {
                return _deathpileGroupTimeout;
            }
            set
            {
                _deathpileGroupTimeout = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _deathpileOtherTimeout = 900;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DeathpileOtherTimeout")]
        public int DeathpileOtherTimeout
        {
            get
            {
                return _deathpileOtherTimeout;
            }
            set
            {
                _deathpileOtherTimeout = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _monsterLootDropTimeout = 60;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MonsterLootDropTimeout")]
        public int MonsterLootDropTimeout
        {
            get
            {
                return _monsterLootDropTimeout;
            }
            set
            {
                _monsterLootDropTimeout = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _monsterTaggingTimeout = 300;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MonsterTaggingTimeout")]
        public int MonsterTaggingTimeout
        {
            get
            {
                return _monsterTaggingTimeout;
            }
            set
            {
                _monsterTaggingTimeout = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _byteHeartbeatInterval = 60;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ByteHeartbeatInterval")]
        public int ByteHeartbeatInterval
        {
            get
            {
                return _byteHeartbeatInterval;
            }
            set
            {
                _byteHeartbeatInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _tickHeartbeatInterval = 60;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("TickHeartbeatInterval")]
        public int TickHeartbeatInterval
        {
            get
            {
                return _tickHeartbeatInterval;
            }
            set
            {
                _tickHeartbeatInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _heartbeatReaperInterval = 5;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("HeartbeatReaperInterval")]
        public int HeartbeatReaperInterval
        {
            get
            {
                return _heartbeatReaperInterval;
            }
            set
            {
                _heartbeatReaperInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _checkpointInterval = 300;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CheckpointInterval")]
        public int CheckpointInterval
        {
            get
            {
                return _checkpointInterval;
            }
            set
            {
                _checkpointInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _regenInterval = 25;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("RegenInterval")]
        public int RegenInterval
        {
            get
            {
                return _regenInterval;
            }
            set
            {
                _regenInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _snoreInterval = 10;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SnoreInterval")]
        public int SnoreInterval
        {
            get
            {
                return _snoreInterval;
            }
            set
            {
                _snoreInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _idleDetectionInterval = 60;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("IdleDetectionInterval")]
        public int IdleDetectionInterval
        {
            get
            {
                return _idleDetectionInterval;
            }
            set
            {
                _idleDetectionInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _mailboxCleanupInterval = 3600;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MailboxCleanupInterval")]
        public int MailboxCleanupInterval
        {
            get
            {
                return _mailboxCleanupInterval;
            }
            set
            {
                _mailboxCleanupInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _merchantInventoryRefreshInterval = 60;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MerchantInventoryRefreshInterval")]
        public int MerchantInventoryRefreshInterval
        {
            get
            {
                return _merchantInventoryRefreshInterval;
            }
            set
            {
                _merchantInventoryRefreshInterval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerIdleCheck = 10;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerIdleCheck")]
        public int PlayerIdleCheck
        {
            get
            {
                return _playerIdleCheck;
            }
            set
            {
                _playerIdleCheck = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _dialogSequenceShared = 5000;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DialogSequenceShared")]
        public int DialogSequenceShared
        {
            get
            {
                return _dialogSequenceShared;
            }
            set
            {
                _dialogSequenceShared = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _dialogSequencePursuits = 5100;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DialogSequencePursuits")]
        public int DialogSequencePursuits
        {
            get
            {
                return _dialogSequencePursuits;
            }
            set
            {
                _dialogSequencePursuits = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _dialogSequenceAsync = 65000;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DialogSequenceAsync")]
        public int DialogSequenceAsync
        {
            get
            {
                return _dialogSequenceAsync;
            }
            set
            {
                _dialogSequenceAsync = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _dialogSequenceHardcoded = 65280;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DialogSequenceHardcoded")]
        public int DialogSequenceHardcoded
        {
            get
            {
                return _dialogSequenceHardcoded;
            }
            set
            {
                _dialogSequenceHardcoded = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _boardMessageResponseSize = 64;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("BoardMessageResponseSize")]
        public int BoardMessageResponseSize
        {
            get
            {
                return _boardMessageResponseSize;
            }
            set
            {
                _boardMessageResponseSize = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _boardMessageCooldown = 60;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("BoardMessageCooldown")]
        public int BoardMessageCooldown
        {
            get
            {
                return _boardMessageCooldown;
            }
            set
            {
                _boardMessageCooldown = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _mailMessageCooldown = 60;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MailMessageCooldown")]
        public int MailMessageCooldown
        {
            get
            {
                return _mailMessageCooldown;
            }
            set
            {
                _mailMessageCooldown = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerMinStat = 1;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMinStat")]
        public int PlayerMinStat
        {
            get
            {
                return _playerMinStat;
            }
            set
            {
                _playerMinStat = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _playerMaxStat = 255;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxStat")]
        public int PlayerMaxStat
        {
            get
            {
                return _playerMaxStat;
            }
            set
            {
                _playerMaxStat = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private uint _playerMinBaseHpMp = 1u;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMinBaseHpMp")]
        public uint PlayerMinBaseHpMp
        {
            get
            {
                return _playerMinBaseHpMp;
            }
            set
            {
                _playerMinBaseHpMp = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private uint _playerMaxBaseHpMp = 4294967295u;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxBaseHpMp")]
        public uint PlayerMaxBaseHpMp
        {
            get
            {
                return _playerMaxBaseHpMp;
            }
            set
            {
                _playerMaxBaseHpMp = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMinDmg = -16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMinDmg")]
        public float PlayerMinDmg
        {
            get
            {
                return _playerMinDmg;
            }
            set
            {
                _playerMinDmg = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMaxDmg = 16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxDmg")]
        public float PlayerMaxDmg
        {
            get
            {
                return _playerMaxDmg;
            }
            set
            {
                _playerMaxDmg = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMinHit = -16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMinHit")]
        public float PlayerMinHit
        {
            get
            {
                return _playerMinHit;
            }
            set
            {
                _playerMinHit = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMaxHit = 16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxHit")]
        public float PlayerMaxHit
        {
            get
            {
                return _playerMaxHit;
            }
            set
            {
                _playerMaxHit = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMinMr = -16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMinMr")]
        public float PlayerMinMr
        {
            get
            {
                return _playerMinMr;
            }
            set
            {
                _playerMinMr = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMaxMr = 16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxMr")]
        public float PlayerMaxMr
        {
            get
            {
                return _playerMaxMr;
            }
            set
            {
                _playerMaxMr = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMinAc = -90F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMinAc")]
        public float PlayerMinAc
        {
            get
            {
                return _playerMinAc;
            }
            set
            {
                _playerMinAc = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMaxAc = 100F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxAc")]
        public float PlayerMaxAc
        {
            get
            {
                return _playerMaxAc;
            }
            set
            {
                _playerMaxAc = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMinRegen = -16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMinRegen")]
        public float PlayerMinRegen
        {
            get
            {
                return _playerMinRegen;
            }
            set
            {
                _playerMinRegen = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _playerMaxRegen = 16F;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PlayerMaxRegen")]
        public float PlayerMaxRegen
        {
            get
            {
                return _playerMaxRegen;
            }
            set
            {
                _playerMaxRegen = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _className0 = "Peasant";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ClassName0")]
        public string ClassName0
        {
            get
            {
                return _className0;
            }
            set
            {
                _className0 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _className1 = "Warrior";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ClassName1")]
        public string ClassName1
        {
            get
            {
                return _className1;
            }
            set
            {
                _className1 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _className2 = "Rogue";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ClassName2")]
        public string ClassName2
        {
            get
            {
                return _className2;
            }
            set
            {
                _className2 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _className3 = "Wizard";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ClassName3")]
        public string ClassName3
        {
            get
            {
                return _className3;
            }
            set
            {
                _className3 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _className4 = "Priest";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ClassName4")]
        public string ClassName4
        {
            get
            {
                return _className4;
            }
            set
            {
                _className4 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _className5 = "Monk";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ClassName5")]
        public string ClassName5
        {
            get
            {
                return _className5;
            }
            set
            {
                _className5 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _levelCircle1 = 11;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LevelCircle1")]
        public int LevelCircle1
        {
            get
            {
                return _levelCircle1;
            }
            set
            {
                _levelCircle1 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _levelCircle2 = 41;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LevelCircle2")]
        public int LevelCircle2
        {
            get
            {
                return _levelCircle2;
            }
            set
            {
                _levelCircle2 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _levelCircle3 = 71;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LevelCircle3")]
        public int LevelCircle3
        {
            get
            {
                return _levelCircle3;
            }
            set
            {
                _levelCircle3 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _levelCircle4 = 99;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LevelCircle4")]
        public int LevelCircle4
        {
            get
            {
                return _levelCircle4;
            }
            set
            {
                _levelCircle4 = value;
            }
        }
    }
}
