//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Spawn", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Spawn
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Loot")]
        public Hybrasyl.Xml.Objects.LootList Loot { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<SpawnCoordinate> _coordinates;
        
        [System.Xml.Serialization.XmlArrayAttribute("Coordinates")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Coordinate", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<SpawnCoordinate> Coordinates
        {
            get
            {
                return _coordinates;
            }
            set
            {
                _coordinates = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Coordinates collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoordinatesSpecified
        {
            get
            {
                return ((this.Coordinates != null) 
                            && (this.Coordinates.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Spawn" /> class.</para>
        /// </summary>
        public Spawn()
        {
            this._coordinates = new System.Collections.Generic.List<SpawnCoordinate>();
            this._setCookies = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.CreatureCookie>();
            this._immunities = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.CreatureImmunity>();
            this._flags = SpawnFlags.Active;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Damage")]
        public SpawnDamage Damage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Defense")]
        public SpawnDefense Defense { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Spec")]
        public SpawnSpec Spec { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Base")]
        public SpawnBase Base { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Hostility")]
        public Hybrasyl.Xml.Objects.CreatureHostilitySettings Hostility { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.CreatureCookie> _setCookies;
        
        [System.Xml.Serialization.XmlArrayAttribute("SetCookies")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Cookie", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.CreatureCookie> SetCookies
        {
            get
            {
                return _setCookies;
            }
            set
            {
                _setCookies = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SetCookies collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SetCookiesSpecified
        {
            get
            {
                return ((this.SetCookies != null) 
                            && (this.SetCookies.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.CreatureImmunity> _immunities;
        
        [System.Xml.Serialization.XmlArrayAttribute("Immunities")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Immunity", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.CreatureImmunity> Immunities
        {
            get
            {
                return _immunities;
            }
            set
            {
                _immunities = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Immunities collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImmunitiesSpecified
        {
            get
            {
                return ((this.Immunities != null) 
                            && (this.Immunities.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Import")]
        public string Import { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private SpawnFlags _flags;
        
        [System.ComponentModel.DefaultValueAttribute(SpawnFlags.Active)]
        [System.Xml.Serialization.XmlAttributeAttribute("Flags")]
        public SpawnFlags Flags
        {
            get
            {
                return _flags;
            }
            set
            {
                _flags = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Flags collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagsSpecified
        {
            get
            {
                return (this.Flags != default(SpawnFlags));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _despawnAfter = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlAttributeAttribute("DespawnAfter")]
        public int DespawnAfter
        {
            get
            {
                return _despawnAfter;
            }
            set
            {
                _despawnAfter = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _despawnLoot = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("DespawnLoot")]
        public bool DespawnLoot
        {
            get
            {
                return _despawnLoot;
            }
            set
            {
                _despawnLoot = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ActiveFrom")]
        public string ActiveFrom { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ActiveTo")]
        public string ActiveTo { get; set; }
    }
}
