// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.74.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class Spawn : HybrasylEntity<Spawn>
{
    #region Private fields
    private LootList _loot;
    private List<SpawnCoordinate> _coordinates;
    private SpawnDamage _damage;
    private SpawnDefense _defense;
    private SpawnSpec _spec;
    private SpawnBase _base;
    private CreatureHostilitySettings _hostility;
    private List<CreatureCookie> _setCookies;
    private List<string> _immunities;
    private string _import;
    private string _name;
    private SpawnFlags _flags;
    private int _despawnAfter;
    private bool _despawnLoot;
    #endregion
    
    public Spawn()
    {
        _flags = SpawnFlags.Active;
        _despawnAfter = 0;
        _despawnLoot = false;
    }
    
    public LootList Loot
    {
        get
        {
            return _loot;
        }
        set
        {
            _loot = value;
        }
    }
    
    [XmlArrayItemAttribute("Coordinate", IsNullable=false)]
    public List<SpawnCoordinate> Coordinates
    {
        get
        {
            return _coordinates;
        }
        set
        {
            _coordinates = value;
        }
    }
    
    public SpawnDamage Damage
    {
        get
        {
            return _damage;
        }
        set
        {
            _damage = value;
        }
    }
    
    public SpawnDefense Defense
    {
        get
        {
            return _defense;
        }
        set
        {
            _defense = value;
        }
    }
    
    public SpawnSpec Spec
    {
        get
        {
            return _spec;
        }
        set
        {
            _spec = value;
        }
    }
    
    public SpawnBase Base
    {
        get
        {
            return _base;
        }
        set
        {
            _base = value;
        }
    }
    
    public CreatureHostilitySettings Hostility
    {
        get
        {
            return _hostility;
        }
        set
        {
            _hostility = value;
        }
    }
    
    [XmlArrayItemAttribute("Cookie", IsNullable=false)]
    public List<CreatureCookie> SetCookies
    {
        get
        {
            return _setCookies;
        }
        set
        {
            _setCookies = value;
        }
    }
    
    [XmlArrayItemAttribute("Immunity", IsNullable=false)]
    public List<string> Immunities
    {
        get
        {
            return _immunities;
        }
        set
        {
            _immunities = value;
        }
    }
    
    [XmlAttribute]
    public string Import
    {
        get
        {
            return _import;
        }
        set
        {
            _import = value;
        }
    }
    
    [XmlAttribute]
    public string Name
    {
        get
        {
            return _name;
        }
        set
        {
            _name = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(SpawnFlags.Active)]
    public SpawnFlags Flags
    {
        get
        {
            return _flags;
        }
        set
        {
            _flags = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(0)]
    public int DespawnAfter
    {
        get
        {
            return _despawnAfter;
        }
        set
        {
            _despawnAfter = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(false)]
    public bool DespawnLoot
    {
        get
        {
            return _despawnLoot;
        }
        set
        {
            _despawnLoot = value;
        }
    }
}
}
#pragma warning restore
