//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o src/Objects -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SpawnBase", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SpawnBase
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("BehaviorSet")]
        public string BehaviorSet { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Level")]
        public string Level { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _weakChance = 0F;
        
        [System.ComponentModel.DefaultValueAttribute(0F)]
        [System.Xml.Serialization.XmlAttributeAttribute("WeakChance")]
        public float WeakChance
        {
            get
            {
                return _weakChance;
            }
            set
            {
                _weakChance = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _strongChance = 0F;
        
        [System.ComponentModel.DefaultValueAttribute(0F)]
        [System.Xml.Serialization.XmlAttributeAttribute("StrongChance")]
        public float StrongChance
        {
            get
            {
                return _strongChance;
            }
            set
            {
                _strongChance = value;
            }
        }
    }
}
