// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.74.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class SpawnGroup : HybrasylEntity<SpawnGroup>
{
    #region Private fields
    private List<Spawn> _spawns;
    private LootList _loot;
    private string _baseLevel;
    private bool _disabled;
    private string _name;
    #endregion
    
    public SpawnGroup()
    {
        _disabled = false;
    }
    
    [XmlArrayItemAttribute(IsNullable=false)]
    public List<Spawn> Spawns
    {
        get
        {
            return _spawns;
        }
        set
        {
            _spawns = value;
        }
    }
    
    public LootList Loot
    {
        get
        {
            return _loot;
        }
        set
        {
            _loot = value;
        }
    }
    
    [XmlAttribute]
    public string BaseLevel
    {
        get
        {
            return _baseLevel;
        }
        set
        {
            _baseLevel = value;
        }
    }
    
    [XmlAttribute]
    [DefaultValue(false)]
    public bool Disabled
    {
        get
        {
            return _disabled;
        }
        set
        {
            _disabled = value;
        }
    }
    
    [XmlAttribute]
    public string Name
    {
        get
        {
            return _name;
        }
        set
        {
            _name = value;
        }
    }
}
}
#pragma warning restore
