//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Hybrasyl.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o /tmp/claude-1000/-home-baughj-repos-xml/91e18c8d-51f4-4f42-8d2e-693476d3c7b5/scratchpad/xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatModifiers", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatModifiers
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElementalModifier> _elementalModifiers;
        
        [System.Xml.Serialization.XmlArrayAttribute("ElementalModifiers")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ElementalModifier", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
        public System.Collections.Generic.List<ElementalModifier> ElementalModifiers
        {
            get
            {
                return _elementalModifiers;
            }
            set
            {
                _elementalModifiers = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ElementalModifiers collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElementalModifiersSpecified
        {
            get
            {
                return ((this.ElementalModifiers != null) 
                            && (this.ElementalModifiers.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StatModifiers" /> class.</para>
        /// </summary>
        public StatModifiers()
        {
            this._elementalModifiers = new System.Collections.Generic.List<ElementalModifier>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseStr")]
        public string BaseStr { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseInt")]
        public string BaseInt { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseWis")]
        public string BaseWis { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseCon")]
        public string BaseCon { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseDex")]
        public string BaseDex { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseHp")]
        public string BaseHp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseMp")]
        public string BaseMp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CurrentHp")]
        public string CurrentHp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CurrentMp")]
        public string CurrentMp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CurrentGold")]
        public string CurrentGold { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CurrentXp")]
        public string CurrentXp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CurrentFaith")]
        public string CurrentFaith { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseHit")]
        public string BaseHit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseDmg")]
        public string BaseDmg { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseAc")]
        public string BaseAc { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseRegen")]
        public string BaseRegen { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseMr")]
        public string BaseMr { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseCrit")]
        public string BaseCrit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseMagicCrit")]
        public string BaseMagicCrit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseInboundDamageToMp")]
        public string BaseInboundDamageToMp { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ElementType _baseOffensiveElement = Hybrasyl.Xml.Objects.ElementType.None;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.ElementType.None)]
        [System.Xml.Serialization.XmlAttributeAttribute("BaseOffensiveElement")]
        public ElementType BaseOffensiveElement
        {
            get
            {
                return _baseOffensiveElement;
            }
            set
            {
                _baseOffensiveElement = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ElementType _baseDefensiveElement = Hybrasyl.Xml.Objects.ElementType.None;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.ElementType.None)]
        [System.Xml.Serialization.XmlAttributeAttribute("BaseDefensiveElement")]
        public ElementType BaseDefensiveElement
        {
            get
            {
                return _baseDefensiveElement;
            }
            set
            {
                _baseDefensiveElement = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseExtraFaith")]
        public string BaseExtraFaith { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ElementType _offensiveElementOverride = Hybrasyl.Xml.Objects.ElementType.None;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.ElementType.None)]
        [System.Xml.Serialization.XmlAttributeAttribute("OffensiveElementOverride")]
        public ElementType OffensiveElementOverride
        {
            get
            {
                return _offensiveElementOverride;
            }
            set
            {
                _offensiveElementOverride = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ElementType _defensiveElementOverride = Hybrasyl.Xml.Objects.ElementType.None;
        
        [System.ComponentModel.DefaultValueAttribute(Hybrasyl.Xml.Objects.ElementType.None)]
        [System.Xml.Serialization.XmlAttributeAttribute("DefensiveElementOverride")]
        public ElementType DefensiveElementOverride
        {
            get
            {
                return _defensiveElementOverride;
            }
            set
            {
                _defensiveElementOverride = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseInboundDamageModifier")]
        public string BaseInboundDamageModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseOutboundDamageModifier")]
        public string BaseOutboundDamageModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseInboundHealModifier")]
        public string BaseInboundHealModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseOutboundHealModifier")]
        public string BaseOutboundHealModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DamageType")]
        public string DamageType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseReflectMagical")]
        public string BaseReflectMagical { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseReflectPhysical")]
        public string BaseReflectPhysical { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseExtraGold")]
        public string BaseExtraGold { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseDodge")]
        public string BaseDodge { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseMagicDodge")]
        public string BaseMagicDodge { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseExtraXp")]
        public string BaseExtraXp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseExtraItemFind")]
        public string BaseExtraItemFind { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseLifeSteal")]
        public string BaseLifeSteal { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaseManaSteal")]
        public string BaseManaSteal { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusStr")]
        public string BonusStr { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusInt")]
        public string BonusInt { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusWis")]
        public string BonusWis { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusCon")]
        public string BonusCon { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusDex")]
        public string BonusDex { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusHp")]
        public string BonusHp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusMp")]
        public string BonusMp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusHit")]
        public string BonusHit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusDmg")]
        public string BonusDmg { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusAc")]
        public string BonusAc { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusRegen")]
        public string BonusRegen { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusMr")]
        public string BonusMr { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusCrit")]
        public string BonusCrit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusMagicCrit")]
        public string BonusMagicCrit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusInboundDamageModifier")]
        public string BonusInboundDamageModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusOutboundDamageModifier")]
        public string BonusOutboundDamageModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusInboundHealModifier")]
        public string BonusInboundHealModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusOutboundHealModifier")]
        public string BonusOutboundHealModifier { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusReflectMagical")]
        public string BonusReflectMagical { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusReflectPhysical")]
        public string BonusReflectPhysical { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusExtraGold")]
        public string BonusExtraGold { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusDodge")]
        public string BonusDodge { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusMagicDodge")]
        public string BonusMagicDodge { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusExtraXp")]
        public string BonusExtraXp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusExtraItemFind")]
        public string BonusExtraItemFind { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusLifeSteal")]
        public string BonusLifeSteal { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusManaSteal")]
        public string BonusManaSteal { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusInboundDamageToMp")]
        public string BonusInboundDamageToMp { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BonusExtraFaith")]
        public string BonusExtraFaith { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Shield")]
        public string Shield { get; set; }
    }
}
