// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.142.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Hybrasyl.Xml.Objects
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
public partial class Use : HybrasylEntity<Use>
{
    #region Private fields
    private string _script;
    private ItemUseTeleport _teleport;
    private ItemUseEffect _effect;
    private ItemUseSound _sound;
    private Statuses _statuses;
    #endregion
    
    public Use()
    {
        _statuses = new Statuses();
    }
    
    public string Script
    {
        get
        {
            return _script;
        }
        set
        {
            _script = value;
        }
    }
    
    public ItemUseTeleport Teleport
    {
        get
        {
            return _teleport;
        }
        set
        {
            _teleport = value;
        }
    }
    
    public ItemUseEffect Effect
    {
        get
        {
            return _effect;
        }
        set
        {
            _effect = value;
        }
    }
    
    public ItemUseSound Sound
    {
        get
        {
            return _sound;
        }
        set
        {
            _sound = value;
        }
    }
    
    public Statuses Statuses
    {
        get
        {
            return _statuses;
        }
        set
        {
            _statuses = value;
        }
    }
}
}
#pragma warning restore
