//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1356.0 using the following command:
// xscgen src/XSD/Castable.xsd src/XSD/Common.xsd src/XSD/Creature.xsd src/XSD/ElementTable.xsd src/XSD/Hybrasyl.xsd src/XSD/Item.xsd src/XSD/Localization.xsd src/XSD/Loot.xsd src/XSD/Map.xsd src/XSD/Nation.xsd src/XSD/Recipe.xsd src/XSD/ServerConfig.xsd src/XSD/Spawns.xsd src/XSD/Status.xsd -o /tmp/claude-1000/-home-baughj-repos-xml/91e18c8d-51f4-4f42-8d2e-693476d3c7b5/scratchpad/xscgen-out -n http://www.hybrasyl.com/XML/Hybrasyl/2020-02=Hybrasyl.Xml.Objects --separateFiles --collectionType=System.Collections.Generic.List`1 --collectionSettersMode=Public --enumCollection
namespace Hybrasyl.Xml.Objects
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1356.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VariantProperties", Namespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VariantProperties
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Appearance")]
        public Appearance Appearance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Damage")]
        public ItemDamage Damage { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ItemFlags _flags;
        
        [System.Xml.Serialization.XmlElementAttribute("Flags")]
        public ItemFlags Flags
        {
            get
            {
                return _flags;
            }
            set
            {
                _flags = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Flags collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagsSpecified
        {
            get
            {
                return (this.Flags != default(ItemFlags));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VariantProperties" /> class.</para>
        /// </summary>
        public VariantProperties()
        {
            this._flags = default(ItemFlags);
            this._tags = new System.Collections.Generic.List<Hybrasyl.Xml.Objects.ItemTag>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Physical")]
        public Physical Physical { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Restrictions")]
        public ItemRestrictions Restrictions { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("Script")]
        public string Script { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Stackable")]
        public Stackable Stackable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StatModifiers")]
        public Hybrasyl.Xml.Objects.StatModifiers StatModifiers { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Hybrasyl.Xml.Objects.ItemTag> _tags;
        
        [System.Xml.Serialization.XmlAttributeAttribute("Tags")]
        public System.Collections.Generic.List<Hybrasyl.Xml.Objects.ItemTag> Tags
        {
            get
            {
                return _tags;
            }
            set
            {
                _tags = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Tags collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TagsSpecified
        {
            get
            {
                return ((this.Tags != null) 
                            && (this.Tags.Count != 0));
            }
        }
    }
}
