name: XML packaging and testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Check out ceridwen
        uses: actions/checkout@v3
        with:
          repository: hybrasyl/xml
          path: ceridwen
      - name: update test settings
        run: cat <<< $(jq '.WorldDataDirectory = "hurr/burr/durr"' tests/xmltest-settings.json) > tests/xmltest-settings.json
      - name: Test
        run: dotnet publish && dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      - name: Codecov
        uses: codecov/codecov-action@v3
        fail_ci_if_error: true
        verbose: true
